server:
  port: 8502

spring:
  application:
    name: service-cart
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.153:8848
        username: nacos
        password: nacos

  data:
    redis:
      host: 192.168.200.153
      port: 6379
