#配置端口号
server:
  port: 8501

# 配置数据库连接信息
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource #连接池名
    driver-class-name: com.mysql.cj.jdbc.Driver #驱动名
    url: jdbc:mysql://192.168.200.153:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC #数据库路径
    username: root #用户名
    password: 123456 #密码
  data:
    redis:
      host: 192.168.200.153
      port: 6379

mybatis:
  mapper-locations: classpath:/mapper/*/*.xml
  config-location: classpath:/mybatis-config.xml

spzx:
  minio:
    endpointUrl: http://192.168.200.153:9000
    accessKey: minioadmin
    secreKey: minioadmin
    bucketName: spzx-bucket

