server:
  port: 8500
spring:
  application:
    name: spzx-server-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.153:8848
        username: nacos
        password: nacos
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]': #跨域
            allowedOriginPatterns: "*"
            # 允许请求中携带的头信息
            allowedHeaders: "*"
            # 运行跨域的请求方式
            allowedMethods: "*"
            # 跨域检测的有效期,单位s
            maxAge: 36000
      routes:
        - id: service-product
          uri: lb://service-product
          predicates:
            - Path=/*/product/**   #断言，当满足这个时，就会到service-product微服务中找
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/*/user/**
        - id: service-cart
          uri: lb://service-cart
          predicates:
            - Path=/api/order/cart/**
        - id: service-order
          uri: lb://service-order
          predicates:
            - Path=/api/order/orderInfo/**
        - id: service-pay
          uri: lb://service-pay
          predicates:
            - Path=/api/order/alipay/**

  data:
    redis:
      host: 192.168.200.153
      port: 6379
